name: create an issue from Jira without a Milestone

on:
    workflow_dispatch:
        inputs:
            issue_key:
                description: 'Jira issue key'
                required: true
            body:
                description: 'Description of the issue'
                required: true
            title:
                description: 'Title of the issue'
                required: true
jobs:
    create_issue:
        runs-on: ubuntu-latest
        steps:
            - name: Create issue with milestone
              uses: actions/github-script@v6
              env:
                BODY: ${{ github.event.inputs.body }}
                  
              with:
                github-token: ${{ secrets.GITHUB_TOKEN }}
                script: |
                    const {BODY} = process.env;
                    const issue = await github.rest.issues.create({
                        owner: context.repo.owner,
                        repo: context.repo.repo,
                        title: '${{ github.event.inputs.title }}', 
                        body: BODY,
                    });
                    
