on:
  issues:
    types: [opened, reopened]

jobs:
  build:
    permissions: write-all
    runs-on: ubuntu-latest
    name: opens Jira issue on Github issue
    steps:
    - name: Login
      uses: atlassian/gajira-login@master
      env:
        JIRA_BASE_URL: ${{ secrets.JIRA_BASE_URL }}
        JIRA_USER_EMAIL: ${{ secrets.JIRA_USER_EMAIL }}
        JIRA_API_TOKEN: ${{ secrets.JIRA_API_TOKEN }}
    - name: Extract branch name
      shell: bash
      run: echo "branch=${GITHUB_HEAD_REF:-${GITHUB_REF#refs/heads/}}" >> $GITHUB_OUTPUT
      id: extract_branch
    
    - name: Create
      id: create
      uses: atlassian/gajira-create@v3
      with:
        project: ES1
        issuetype: issue
        summary: New Issue from ${{ github.actor}} named ${{ github.event.issue.title }} in ${{ github.repository }} branch ${{ steps.extract_branch.outputs.branch }}
        description: ${{ github.event.issue.body }}
        
    -  name: Add labels
       uses: actions-cool/issues-helper@v3.5.2
       with:
          actions: 'add-labels'
          token: ${{ secrets.GITHUB_TOKEN }}
          issue-number: ${{ github.event.issue.number }}
          labels: steps.create.outputs.issue
    - name: Log created issue
      run: echo "Issue ${{ steps.create.outputs.issue }} was created"
